"""Add read stats

Revision ID: 206be8bfcce8
Revises: 570751bc1e2b
Create Date: 2023-09-05 09:15:10.765549

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "206be8bfcce8"
down_revision = "570751bc1e2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contentmodelread",
        sa.Column("aid", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=True),
        sa.Column("href", sa.String(length=500), nullable=True),
        sa.Column("model_id", sa.BigInteger(), nullable=False),
        sa.Column("read_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("aid", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contentmodelread")
    # ### end Alembic commands ###
