"""Add read stats word_count

Revision ID: 5394c1f09714
Revises: 206be8bfcce8
Create Date: 2023-09-28 14:22:55.420987

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5394c1f09714"
down_revision = "206be8bfcce8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contentmodelread", sa.Column("word_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contentmodelread", "word_count")
    # ### end Alembic commands ###
