"""Add activity stats

Revision ID: 570751bc1e2b
Revises: 43735f277da4
Create Date: 2023-01-29 02:30:52.278691

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "570751bc1e2b"
down_revision = "43735f277da4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "useractivity",
        sa.Column("aid", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_type", sa.SmallInteger(), nullable=False),
        sa.Column("activity_start", sa.BigInteger(), nullable=False),
        sa.Column("activity_end", sa.BigInteger(), nullable=False),
        sa.Column("data", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("aid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("useractivity")
    # ### end Alembic commands ###
