ARG TRANSCROBES_DOCKER_REPO
ARG TRANSCROBES_BACKEND_IMAGE_TAG
FROM ${TRANSCROBES_DOCKER_REPO:-transcrobes}/base:${TRANSCROBES_BACKEND_IMAGE_TAG:-$GIT_VERSION}

LABEL maintainer="Anton Melser <anton@transcrob.es>"

ENV C_FORCE_ROOT=1

WORKDIR /app

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

COPY ./backend/app/fworker-start.sh /fworker-start.sh
RUN chmod +x /fworker-start.sh

CMD ["/bin/bash", "/fworker-start.sh"]
