ARG TRANSCROBES_DOCKER_REPO

FROM ${TRANSCROBES_DOCKER_REPO:-transcrobes}/transcrobes-base

LABEL maintainer="Anton Melser <anton@transcrob.es>"

ENV C_FORCE_ROOT=1

WORKDIR /app

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

COPY ./backend/app/sworker-start.sh /sworker-start.sh
RUN chmod +x /sworker-start.sh

CMD ["/bin/bash", "/sworker-start.sh"]
