ARG TRANSCROBES_DOCKER_REPO
FROM ${TRANSCROBES_DOCKER_REPO:-transcrobes}/transcrobes-base

LABEL maintainer="Anton Melser <anton@transcrob.es>"

ENV C_FORCE_ROOT=1

WORKDIR /app

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

COPY ./backend/app/fworker-start.sh /fworker-start.sh
RUN chmod +x /fworker-start.sh

CMD ["/bin/bash", "/fworker-start.sh"]
