ARG TRANSCROBES_DOCKER_REPO
ARG TRANSCROBES_BACKEND_IMAGE_TAG
FROM ${TRANSCROBES_DOCKER_REPO:-transcrobes}/base:${TRANSCROBES_BACKEND_IMAGE_TAG:-$GIT_VERSION}

LABEL maintainer="Anton Melser <anton@transcrob.es>"

ENV C_FORCE_ROOT=1

WORKDIR /app

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

COPY ./backend/app/sworker-start.sh /sworker-start.sh
RUN chmod +x /sworker-start.sh

CMD ["/bin/bash", "/sworker-start.sh"]
