ARG TRANSCROBES_DOCKER_REPO
ARG TRANSCROBES_BASE_IMAGE_TAG
FROM ${TRANSCROBES_DOCKER_REPO:-transcrobes}/transcrobes-base:${TRANSCROBES_BASE_IMAGE_TAG:-latest}

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

WORKDIR /app/

COPY ./backend/app/start-reload.sh ./backend/app/start-uvicorn.sh \
  ./backend/app/start.sh ./backend/app/gunicorn_conf.py /
RUN chmod +x /start.sh /start-reload.sh /start-uvicorn.sh

CMD ["/bin/bash", "/start-uvicorn.sh"]
