{{- if and .Values.corenlpEn.enabled .Values.corenlpEn.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.corenlpEn.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "transcrobes.corenlpEn.fullname" . }}-ingress
  labels:
    {{- include "transcrobes.transcrobes.labels" . | nindent 4 }}

spec:
  ingressClassName: {{ .Values.corenlpEn.ingress.className }}
  rules:
    - host: {{ .Values.corenlpEn.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "transcrobes.corenlpEn.fullname" . }}
                port:
                  number: {{ .Values.corenlpEn.service.servicePort }}
{{- end }}
