{{- if and .Values.transcrobes.enabled .Values.statsdb.persistence.enabled .Values.transcrobes.local.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transcrobes-transcrobes-statsdb
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    type: local
    {{- include "transcrobes.transcrobes.labels" . | nindent 4 }}
spec:
  storageClassName: manual-statsdb
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.statsdb.persistence.size }}
status: {}
{{- end }}
