{{- if and .Values.transcrobes.enabled .Values.pgha.persistence.enabled .Values.transcrobes.local.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transcrobes-transcrobes-db
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    type: local
    {{- include "transcrobes.transcrobes.labels" . | nindent 4 }}
spec:
  storageClassName: manual-db
  capacity:
    storage: {{ .Values.pgha.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/transcrobes/volumes/transcrobes-db"
{{- end }}
