{{- if .Values.transcrobes.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transcrobes.transcrobes.fullname" . }}
  labels:
    {{- include "transcrobes.transcrobes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.transcrobes.replicaCount }}
  {{- if .Values.transcrobes.strategy }}
  strategy:
{{ toYaml .Values.transcrobes.strategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "transcrobes.transcrobes.matchLabels" . | nindent 6 }}
      # release: prometheus
  template:
    metadata:
    {{- if .Values.transcrobes.podAnnotations }}
      annotations:
{{ toYaml .Values.transcrobes.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "transcrobes.transcrobes.labels" . | nindent 8 }}
        # release: prometheus
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              component: transcrobes

      initContainers:
        - name: check-db-ready
          image: postgres:16
          command: ['sh', '-c',
            'until psql -c "select 1;";
            do echo waiting for database; sleep 2; done;']
          env:
            - name: PGUSER
              value: "{{ .Values.pgha.postgresql.username }}"
            - name: PGDATABASE
              value: "{{ .Values.pgha.postgresql.database }}"
            - name: PGPASSWORD
              value: "{{ .Values.pgha.postgresql.password }}"
            - name: PGHOST
              value: {{ .Values.transcrobes.overrideDBHost | default (printf "%s-pgha-pgpool" .Release.Name) }}

      containers:
        - name: {{ template "transcrobes.name" . }}-{{ .Values.transcrobes.name }}
          image: {{ include "transcrobes.image" . }}
          imagePullPolicy: {{ .Values.transcrobes.image.pullPolicy | quote }}

          {{- if .Values.faustworker.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.faustworker.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.faustworker.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.faustworker.command "context" $) | nindent 12 }}
          {{- else }}
          command: ["/bin/bash", "/start-uvicorn.sh"]
          {{- end }}
          {{- if .Values.faustworker.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.faustworker.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.faustworker.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.faustworker.args "context" $) | nindent 12 }}
          {{- end }}

          livenessProbe:
            httpGet:
              path: /api/v1/utils/hello
              port: http
              httpHeaders:
                - name: Host
                  value: "{{ .Values.transcrobes.haHost }}"
            timeoutSeconds: {{ .Values.transcrobes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.transcrobes.liveness.periodSeconds }}
            initialDelaySeconds: {{ .Values.transcrobes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.transcrobes.liveness.failureThreshold }}

          startupProbe:
            httpGet:
              host:
              scheme: HTTP
              port: http
              path: /api/v1/enrich/load_definitions_cache
              httpHeaders:
                - name: Host
                  value: "{{ .Values.transcrobes.haHost }}"
            timeoutSeconds: {{ .Values.transcrobes.startup.timeoutSeconds }}
            periodSeconds: {{ .Values.transcrobes.startup.periodSeconds }}
            initialDelaySeconds: {{ .Values.transcrobes.startup.initialDelaySeconds }}
            failureThreshold: {{ .Values.transcrobes.startup.failureThreshold }}

          ports:
            - name: http
              containerPort: {{ .Values.transcrobes.application.listenPort }}
              protocol: TCP
          env:
            - name: TRANSCROBES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TRANSCROBES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TRANSCROBES_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: TRANSCROBES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: TRANSCROBES_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- range $key, $value := .Values.transcrobes.extraEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: PYTHONUNBUFFERED  # MUST put or no logs printed to kube, but probably should be in values
              value: "0"
            - name: POSTGRES_USER
              value: "{{ .Values.pgha.postgresql.username }}"
            - name: POSTGRES_DB
              value: "{{ .Values.pgha.postgresql.database }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.pgha.postgresql.password }}"

            - name: POSTGRES_SERVER
              value: {{ .Values.transcrobes.overrideDBHost | default (printf "%s-pgha-pgpool" .Release.Name) }}
            - name: POSTGRES_PORT
              value: "{{ .Values.pgha.service.ports.postgresql }}"

            - name: STATS_POSTGRES_USER
              value: "{{ .Values.statsdb.postgresql.username }}"
            - name: STATS_POSTGRES_DB
              value: "{{ .Values.statsdb.postgresql.database }}"
            - name: STATS_POSTGRES_PASSWORD
              value: "{{ .Values.statsdb.postgresql.password }}"
            - name: STATS_POSTGRES_SERVER
              value: {{ .Values.transcrobes.overrideStatsDBHost | default (printf "%s-statsdb-pgpool" .Release.Name) }}
            - name: STATS_POSTGRES_PORT
              value: "{{ .Values.statsdb.service.ports.postgresql }}"

            - name: MEDIA_ROOT
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.persistence.mediaPath }}"
            - name: DATA_ROOT
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.persistence.dataPath }}"
            - name: SYSTEM_HOSTS
              value: {{ include "transcrobes.transcrobes.fullname" . }},{{ include "transcrobes.transcrobes.reallyFullname" . }}
            - name: IMPORT_MAX_UPLOAD_SIZE_KB
              value: "{{ .Values.transcrobes.application.imports.maxListImportSizeKB }}"
            - name: NODE_HOSTS
              value: {{ .Values.transcrobes.nodeHosts | toJson | squote }}
            - name: SERVER_NAME
              value: {{ include "transcrobes.transcrobes.reallyFullname" . }}
            - name: HA_HOST
              value: "{{ .Values.transcrobes.haHost }}"
            - name: PER_DOMAIN
              value: {{ .Values.transcrobes.perDomain | toJson | squote }}
            - name: SERVER_HOST
              value: "http{{ if .Values.transcrobes.ingress.tls.enabled }}s{{ end }}://{{ .Values.transcrobes.haHost }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.transcrobes.secretKeySecretName }}
                  key: secret-key
            {{- if gt .Values.transcrobes.application.webConcurrency 0.0 }}
            - name: WEB_CONCURRENCY
              value: "{{ .Values.transcrobes.application.webConcurrency }}"
            {{ else }}
            - name: MAX_WORKERS
              value: "{{ .Values.transcrobes.application.maxWorkers }}"
            - name: WORKERS_PER_CORE
              value: "{{ .Values.transcrobes.application.workersPerCore }}"
            {{- end }}
            - name: GUNICORN_TIMEOUT
              value: "{{ .Values.transcrobes.application.gunicornTimeout }}"
            - name: LISTEN_ADDRESS
              value: "{{ .Values.transcrobes.application.listenAddress }}"
            - name: LISTEN_PORT
              value: "{{ .Values.transcrobes.application.listenPort }}"

            {{- if .Values.transcrobes.debug }}
            - name: DEBUG
              value: "True"
            {{- end }}

            - name: BING_SUBSCRIPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.transcrobes.bingSubscriptionKeySecretName }}
                  key: bing-api-token
            - name: BING_API_HOST
              value: "{{ .Values.transcrobes.bingApiHost }}"
            - name: BING_TRANSLATOR_INMEM
              value: "{{ .Values.transcrobes.bingTranslator.inmem }}"
            - name: BING_TRANSLITERATOR_INMEM
              value: "{{ .Values.transcrobes.bingTransliterator.inmem }}"

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.transcrobes.openaiApiKeySecretName }}
                  key: openai-api-token

            - name: EN_CORENLP_HOST
              value: {{ include "transcrobes.corenlpEn.fullname" . }}
            - name: EN_ZH_ABC_DICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.enZhAbcDict.path }}"
            - name: EN_ZH_ABC_DICT_INMEM
              value: "{{ .Values.transcrobes.enZhAbcDict.inmem }}"
            - name: EN_SUBTLEX_FREQ_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.enSubtlexFreq.path }}"
            - name: EN_SUBTLEX_FREQ_INMEM
              value: "{{ .Values.transcrobes.enSubtlexFreq.inmem }}"

            - name: ZH_CORENLP_HOST
              value: {{ include "transcrobes.corenlpZh.fullname" . }}
            - name: ZH_EN_CEDICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhEnCedict.path }}"
            - name: ZH_EN_CEDICT_INMEM
              value: "{{ .Values.transcrobes.zhEnCedict.inmem }}"
            - name: ZH_EN_ABC_DICT_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhEnAbcDict.path }}"
            - name: ZH_EN_ABC_DICT_INMEM
              value: "{{ .Values.transcrobes.zhEnAbcDict.inmem }}"
            - name: ZH_HSK_LISTS_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhHskLists.path }}"
            - name: ZH_HSK_LISTS_INMEM
              value: "{{ .Values.transcrobes.zhHskLists.inmem }}"
            - name: ZH_SUBTLEX_FREQ_PATH
              value: "{{ .Values.transcrobes.persistence.dataRoot }}{{ .Values.transcrobes.zhSubtlexFreq.path }}"
            - name: ZH_SUBTLEX_FREQ_INMEM
              value: "{{ .Values.transcrobes.zhSubtlexFreq.inmem }}"

            - name: BROACASTER_MESSAGING_LAYER
              value: "{{ .Values.transcrobes.broadcasterMessagingLayer }}"
            - name: PROJECT_NAME
              value: "{{ .Values.transcrobes.projectName }}"
            - name: FIRST_SUPERUSER
              value: "{{ .Values.transcrobes.firstSuperuser }}"
            - name: FIRST_SUPERUSER_PASSWORD
              value: "{{ .Values.transcrobes.firstSuperuserPassword }}"

            - name: SMTP_TLS
              value: "{{ .Values.transcrobes.email.smtpTls }}"
            - name: SMTP_PORT
              value: "{{ .Values.transcrobes.email.smtpPort }}"
            - name: SMTP_HOST
              value: "{{ .Values.transcrobes.email.smtpHost }}"
            - name: SMTP_USER
              value: "{{ .Values.transcrobes.email.smtpUser }}"
            - name: SMTP_PASSWORD
              value: "{{ .Values.transcrobes.email.smtpPassword }}"
            - name: EMAILS_FROM_EMAIL
              value: "{{ .Values.transcrobes.email.emailsFromEmail }}"
            - name: EMAILS_FROM_NAME
              value: "{{ .Values.transcrobes.email.emailsFromName }}"
            - name: EMAILS_ENABLED
              value: "{{ .Values.transcrobes.email.enabled }}"
            - name: EMAIL_RESET_TOKEN_EXPIRE_HOURS
              value: "{{ .Values.transcrobes.email.emailResetTokenExpireHours }}"
            - name: EMAIL_TEMPLATES_DIR
              value: "{{ .Values.transcrobes.email.emailTemplatesDir }}"
            - name: EMAIL_TEST_USER
              value: "{{ .Values.transcrobes.email.emailTestUser }}"

            - name: FAUST_HOST
              value: {{ include "transcrobes.faustworker.fullname" . }}

            - name: USERS_OPEN_REGISTRATION
              value: "{{ .Values.transcrobes.usersOpenRegistration }}"

            - name: SENTRY_DSN
              value: "{{ .Values.transcrobes.sentryDsn }}"

            - name: TRACKING_KEY
              value: "{{ .Values.transcrobes.tracking.key }}"
            - name: TRACKING_ENDPOINT
              value: "{{ .Values.transcrobes.tracking.endpoint }}"

            {{- if .Values.kafka.enabled }}
            - name: KAFKA_BROKER
              value: {{ .Values.transcrobes.overrideKafkaHost | default .Values.kafka.fullnameOverride }}
            {{- end }}


      {{- if or .Values.transcrobes.persistence.enabled (not (empty .Values.transcrobes.local.srcFrom)) }}
          volumeMounts:
      {{- if .Values.transcrobes.local.srcFrom }}
          - name: src
            mountPath: /app
      {{- end }}
      {{- if .Values.transcrobes.persistence.enabled }}
          - mountPath: "{{ .Values.transcrobes.persistence.dataRoot }}"
            name: {{ include "transcrobes.transcrobes.fullname" . }}
      {{- end }}
      volumes:
      {{- if .Values.transcrobes.persistence.enabled }}
        - name: {{ include "transcrobes.transcrobes.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "transcrobes.transcrobes.fullname" . }}
      {{- end }}
      {{- if .Values.transcrobes.local.srcFrom }}
        - name: src
          hostPath:
            path: {{ .Values.transcrobes.local.srcFrom }}
            type: DirectoryOrCreate
      {{- end }}
      {{- end }}


      # {{- if .Values.transcrobes.persistence.enabled }}
      #     volumeMounts:
      #     - mountPath: "{{ .Values.transcrobes.persistence.dataRoot }}"
      #       name: {{ include "transcrobes.transcrobes.fullname" . }}
      # volumes:
      #   - name: {{ include "transcrobes.transcrobes.fullname" . }}
      #     persistentVolumeClaim:
      #       claimName: {{ include "transcrobes.transcrobes.fullname" . }}-pvc
      # {{- end }}

      restartPolicy: Always
status: {}
{{- end }}
