# k3d configuration file
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: transcrobes
servers: 1
agents: 1
kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6445"
image: rancher/k3s:v1.28.2-k3s1

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 9100:31000
    nodeFilters:
      - agent:0
  - port: 9101:31001
    nodeFilters:
      - agent:0

env:
  - envVar: name=transcrobes
    nodeFilters:
      - all

options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false

  k3s:
    extraArgs:
      - arg: "--tls-san=127.0.0.1"
        nodeFilters:
          - server:*
    nodeLabels:
      - label: agent=one
        nodeFilters:
          - agent:0
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    labels:
      - label: agent=docker-one
        nodeFilters:
          - agent:0
