# k3d configuration file
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: transcrobes
servers: 1
kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6446"
image: rancher/k3s:v1.29.0-k3s1

registries: # define how registries should be created or used
  use:
    - k3d-registry.localhost:5111

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 30432:30432
    nodeFilters:
      - loadbalancer
  - port: 30433:30433
    nodeFilters:
      - loadbalancer

env:
  - envVar: name=transcrobes
    nodeFilters:
      - all

options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false

  k3s:
    extraArgs:
      - arg: "--tls-san=127.0.0.1"
        nodeFilters:
          - server:*
    # nodeLabels:
    #   - label: agent=one
    #     nodeFilters:
    #       - agent:0
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
  # runtime:
  #   labels:
  #     - label: agent=docker-one
  #       nodeFilters:
  #         - agent:0
