"""Reimplement English

Revision ID: 077b4277d185
Revises: f6f1f75739c6
Create Date: 2022-10-11 09:00:13.207340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "077b4277d185"
down_revision = "f6f1f75739c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encmulookup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.String(length=2000), nullable=False),
        sa.Column("response_json", sa.String(length=25000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encmulookup_source_text"), "encmulookup", ["source_text"], unique=False)
    op.create_table(
        "ensubtlexlookup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.String(length=2000), nullable=False),
        sa.Column("response_json", sa.String(length=25000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ensubtlexlookup_source_text"), "ensubtlexlookup", ["source_text"], unique=False)
    op.create_table(
        "enzhhansabclookup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.String(length=2000), nullable=False),
        sa.Column("response_json", sa.String(length=25000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_enzhhansabclookup_source_text"), "enzhhansabclookup", ["source_text"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enzhhansabclookup_source_text"), table_name="enzhhansabclookup")
    op.drop_table("enzhhansabclookup")
    op.drop_index(op.f("ix_ensubtlexlookup_source_text"), table_name="ensubtlexlookup")
    op.drop_table("ensubtlexlookup")
    op.drop_index(op.f("ix_encmulookup_source_text"), table_name="encmulookup")
    op.drop_table("encmulookup")
    # ### end Alembic commands ###
