"""add first_success_date to card

Revision ID: 425730afbbcd
Revises: 563a8fb92548
Create Date: 2021-11-23 02:59:55.431313

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "425730afbbcd"
down_revision = "563a8fb92548"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card", sa.Column("first_success_date", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card", "first_success_date")
    # ### end Alembic commands ###
