"""Add en zhhans English

Revision ID: 5f9adbe6b448
Revises: 077b4277d185
Create Date: 2022-10-11 12:23:39.208046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5f9adbe6b448"
down_revision = "077b4277d185"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enzhhansgooglookup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.String(length=2000), nullable=False),
        sa.Column("response_json", sa.String(length=25000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_enzhhansgooglookup_source_text"), "enzhhansgooglookup", ["source_text"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enzhhansgooglookup_source_text"), table_name="enzhhansgooglookup")
    op.drop_table("enzhhansgooglookup")
    # ### end Alembic commands ###
