"""test add lower indexes

Revision ID: 770d8836cf2f
Revises: be3e12a5916b
Create Date: 2022-10-24 09:48:34.697600

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "770d8836cf2f"
down_revision = "be3e12a5916b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_bingapilookup_source_text_lower"),
        "bingapilookup",
        [sa.text("lower('source_text')"), "from_lang", "to_lang"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bingapitranslation_source_text_lower"),
        "bingapitranslation",
        [sa.text("lower('source_text')"), "from_lang", "to_lang"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bingapitransliteration_source_text_lower"),
        "bingapitransliteration",
        [sa.text("lower('source_text')"), "from_lang", "to_lang"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cacheddefinition_source_text_lower"),
        "cacheddefinition",
        [sa.text("lower('source_text')"), "from_lang", "to_lang"],
        unique=False,
    )

    op.create_index(
        op.f("ix_zhhsklookup_source_text_lower"), "zhhsklookup", [sa.text("lower('source_text')")], unique=False
    )
    op.create_index(
        op.f("ix_zhsubtlexlookup_source_text_lower"), "zhsubtlexlookup", [sa.text("lower('source_text')")], unique=False
    )
    op.create_index(
        op.f("ix_zhhansenabclookup_source_text_lower"),
        "zhhansenabclookup",
        [sa.text("lower('source_text')")],
        unique=False,
    )
    op.create_index(
        op.f("ix_zhhansenccclookup_source_text_lower"),
        "zhhansenccclookup",
        [sa.text("lower('source_text')")],
        unique=False,
    )
    op.create_index(
        op.f("ix_enzhhansabclookup_source_text_lower"),
        "enzhhansabclookup",
        [sa.text("lower('source_text')")],
        unique=False,
    )
    op.create_index(
        op.f("ix_enzhhansgooglookup_source_text_lower"),
        "enzhhansgooglookup",
        [sa.text("lower('source_text')")],
        unique=False,
    )
    op.create_index(
        op.f("ix_ensubtlexlookup_source_text_lower"), "ensubtlexlookup", [sa.text("lower('source_text')")], unique=False
    )
    op.create_index(
        op.f("ix_encmulookup_source_text_lower"), "encmulookup", [sa.text("lower('source_text')")], unique=False
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bingapilookup_source_text_lower"), table_name="bingapilookup")
    op.drop_index(op.f("ix_bingapitranslation_source_text_lower"), table_name="bingapitranslation")
    op.drop_index(op.f("ix_bingapitransliteration_source_text_lower"), table_name="bingapitransliteration")
    op.drop_index(op.f("ix_cacheddefinition_source_text_lower"), table_name="cacheddefinition")
    op.drop_index(op.f("ix_zhhsklookup_source_text_lower"), table_name="zhhsklookup")
    op.drop_index(op.f("ix_zhsubtlexlookup_source_text_lower"), table_name="zhsubtlexlookup")
    op.drop_index(op.f("ix_zhhansenabclookup_source_text_lower"), table_name="zhhansenabclookup")
    op.drop_index(op.f("ix_zhhansenccclookup_source_text_lower"), table_name="zhhansenccclookup")
    op.drop_index(op.f("ix_enzhhansabclookup_source_text_lower"), table_name="enzhhansabclookup")
    op.drop_index(op.f("ix_enzhhansgooglookup_source_text_lower"), table_name="enzhhansgooglookup")
    op.drop_index(op.f("ix_ensubtlexlookup_source_text_lower"), table_name="ensubtlexlookup")
    op.drop_index(op.f("ix_encmulookup_source_text_lower"), table_name="encmulookup")

    # ### end Alembic commands ###
