"""Added is_default column to userlist for better default lists

Revision ID: a2798472ac31
Revises: cd0ae0099bd7
Create Date: 2021-12-08 02:35:23.712491

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a2798472ac31"
down_revision = "cd0ae0099bd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userlist", sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userlist", "is_default")
    # ### end Alembic commands ###
