"""Add import/content source_url and extra_data

Revision ID: bc519998700d
Revises: c02fc278261c
Create Date: 2023-03-30 05:22:52.836367

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc519998700d"
down_revision = "c02fc278261c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("source_url", sa.Text(), nullable=True))
    op.add_column("content", sa.Column("extra_data", sa.Text(), nullable=True))
    op.add_column("import", sa.Column("source_url", sa.Text(), nullable=True))
    op.add_column("import", sa.Column("extra_data", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import", "extra_data")
    op.drop_column("import", "source_url")
    op.drop_column("content", "extra_data")
    op.drop_column("content", "source_url")
    # ### end Alembic commands ###
