"""Add en zhhans English bis

Revision ID: be3e12a5916b
Revises: 5f9adbe6b448
Create Date: 2022-10-18 13:47:01.533958

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be3e12a5916b"
down_revision = "5f9adbe6b448"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userlist", sa.Column("from_lang", sa.String(length=20), server_default="zh-Hans", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userlist", "from_lang")
    # ### end Alembic commands ###
