"""Add streamdetails

Revision ID: c02fc278261c
Revises: ee6c1c9714dc
Create Date: 2023-03-27 03:56:06.675091

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c02fc278261c"
down_revision = "ee6c1c9714dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streamdetails",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("imdb_id", sa.Text(), nullable=True),
        sa.Column("streamer", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("streamer_id", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("subtitles", sa.Text(), nullable=True),
        sa.Column("stream_type", sa.Text(), nullable=False),
        sa.Column("season_id", sa.Text(), nullable=True),
        sa.Column("season_title", sa.Text(), nullable=True),
        sa.Column("season_short_name", sa.Text(), nullable=True),
        sa.Column("season_number", sa.Text(), nullable=True),
        sa.Column("season_year", sa.Integer(), nullable=True),
        sa.Column("episode", sa.Integer(), nullable=True),
        sa.Column("episode_title", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("show_id", sa.Text(), nullable=True),
        sa.Column("show_title", sa.Text(), nullable=True),
        sa.Column("original_title", sa.Text(), nullable=True),
        sa.Column("show_genre", sa.Text(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column(
            "activate_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("deactivate_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["authuser.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["authuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_streamdetails_updated_at"), "streamdetails", ["updated_at"], unique=False)
    op.create_table(
        "streamdetails_content",
        sa.Column("streamdetails_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
        ),
        sa.ForeignKeyConstraint(
            ["streamdetails_id"],
            ["streamdetails.id"],
        ),
        sa.PrimaryKeyConstraint("streamdetails_id", "content_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("streamdetails_content")
    op.drop_index(op.f("ix_streamdetails_updated_at"), table_name="streamdetails")
    op.drop_table("streamdetails")
    # ### end Alembic commands ###
