"""Add survey lang pair data

Revision ID: c7e19df869b4
Revises: a0d6e5ff36a2
Create Date: 2022-11-10 03:21:48.383885

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7e19df869b4"
down_revision = "a0d6e5ff36a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("survey", sa.Column("from_lang", sa.String(length=20), server_default="zh-Hans", nullable=False))
    op.add_column("survey", sa.Column("to_lang", sa.String(length=20), server_default="en", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("survey", "to_lang")
    op.drop_column("survey", "from_lang")
    # ### end Alembic commands ###
