"""Allow multiple levels of word-knowing at list creation

Revision ID: cbffb9fa8161
Revises: c15f86274630
Create Date: 2022-01-15 06:28:35.192860

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbffb9fa8161"
down_revision = "c15f86274630"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userlist", sa.Column("word_knowledge", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userlist", "word_knowledge")
    # ### end Alembic commands ###
