"""Added recentsentences table

Revision ID: cd0ae0099bd7
Revises: 425730afbbcd
Create Date: 2021-12-03 09:15:51.591910

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd0ae0099bd7"
down_revision = "425730afbbcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userrecentsentences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lz_content", sa.String(length=25000), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["authuser.id"], initially="DEFERRED", deferrable=True),
        sa.ForeignKeyConstraint(["word_id"], ["bingapilookup.id"], initially="DEFERRED", deferrable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "word_id"),
    )
    op.create_index(op.f("ix_userrecentsentences_updated_at"), "userrecentsentences", ["updated_at"], unique=False)
    op.create_index(op.f("ix_userrecentsentences_user_id"), "userrecentsentences", ["user_id"], unique=False)
    op.create_index(op.f("ix_userrecentsentences_word_id"), "userrecentsentences", ["word_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userrecentsentences_word_id"), table_name="userrecentsentences")
    op.drop_index(op.f("ix_userrecentsentences_user_id"), table_name="userrecentsentences")
    op.drop_index(op.f("ix_userrecentsentences_updated_at"), table_name="userrecentsentences")
    op.drop_table("userrecentsentences")
    # ### end Alembic commands ###
